title: "100Starlings"
email: "info@100starlings.com"
description: >
  We are a cooperative of like minded professionals skilled at solving problems
  and creating excellent products for today's digital world.
url: "http://www.100starlings.com"
plugins:
  - jekyll-sitemap
  - jekyll-feed
github_username: "100Starlings"
